### ISSUE TITLE
Přidat víc layoutů pro stoly

### ISSUE THREAD

**Issue by lrolecek** [benabraham/listecky#15]
Přidat další varianty stolů - určitě 6 míst, možná 8 míst, víc?

Nevím, jestli by nebylo lepší neurčovat v konfiguraci místnosti stůl jako deskType, ale přímo mít u stolu parametry chairs a shape. Je to přehlednější a pochopitelnější. Sice potenciálně hrozí, že v css nebudou definice pro zobrazení daného tvaru s daným počtem židlí, ale to se dá doplňovat průběžně podle potřeby.

**Comment by benabraham** [comment]
Počítám se stolem, který bude až do kraje "buňky layoutu" takže bude nějaký maximální počet míst (spíš 6 než 8, ale zkusíme) a pak si holt dáš tyhle typy stolu vedle sebe. Ty layouty budou taky zahrnovat židle na různých stranách stolů.

ad datová struktura, asi to udělám plošší jak navrhuješ, hlavně s tou novou konfigurací to nebude takovej opruz

**Comment by lrolecek** [comment]
Jasně. Maximálně jsem měl zatím 6 holek u stolu, takže v tom nevidím problém. 

Ty přesně vypadající tvary stolů a umístění židlí u nich bych viděl spíš jako třešničku na dortu. Hlavní je číslo stolu, jeho přibližná lokace v místnosti a spravný počet židlí. Ostatní jsou už jen drobnosti.

**Comment by benabraham** [comment]
Layouty tam jsou, viz https://listecky.herokuapp.com, kde jsou demonstrovány všechny aktuální možnosti. Plus to jde otočit libovolně.
