### ISSUE TITLE
Přidat lektorovi tlačítko pro stav "je přestávka"

### ISSUE THREAD

**Issue by lrolecek** [benabraham/listecky#16]
Momentálně má lektor k dispozici 2 stavy:
- probíhá výklad
- výklad skončil, zadal jsem úkol

Možná by se hodilo přidat ještě stav "Je přestávka". 

Stačí jen takhle jednoduše, pomocí okýnka pro posílání zpráv můžu pak odeslat, jak dlouhá přestávka je.

**Comment by benabraham** [comment]
Udělal jsem to i s nastavením času přestávky a odpočtem.
