### ISSUE TITLE
Logování času a export dat

### ISSUE THREAD

**Issue by benabraham** [benabraham/listecky#30]
na /export/

FYI @Kout

**Comment by Kout** [comment]
:+1:

**Comment by benabraham** [comment]
Samozřejmě je to jen nahrubo, než to vypneš/vypne heroku, je potřeba tam vlízt a zkopírovat si ;) Ale jde to.

**Comment by Kout** [comment]
Bohatě stačí. Respl. stačí nezapomenout. Zatímco při průběžném záznamu, zapomeneš zcela určitě.
