### ISSUE TITLE
Refaktoring RFC

### ISSUE THREAD

**Issue by iBobik** [benabraham/listecky#31]
# Motivace / pain

- chybějící persistence konfigurace termínu (obtížný rozvoj, chystání předem)
- úprava stolů vyžaduje vlastní deploy #17
- úkoly jsou uloženy v repozitáři aplikace → obtížná údržba 

# Řešení

- Použít framework, který (ideálně out of box) řeší persistenci datových struktur včetně jejich real-time synchronizace mezi klienty (Meteor?)
- úkoly načítat z repozitáře zadaného u termínu (typicky ten se slajdy v Reveal)
  - možná rovnou ze slajdů (speciální sekce v md slajdu s úkolem), protože by se to parádně udržovalo 
- konečně to mít na dobře zapamatovatelné adrese (třeba listecky.czechitas.cz), takže nepotřebujeme zkracovače

## Routy 

- `/add-term` a `/%tid/config`: Přidání a editace termínu. Obsahuje formulář s:
  - `tid` libovolný slug, který pak bude v URL, slouží zároveň jako heslo pro účastnice k přístupu do termínu. Ideálně něco krátkého, ale rozumně bezpečného. Oproti jiným způsobům zabezpečení je škálovatelné podle míry rizika - dnes není problém, ale až se adresa aplikace proflákne a objeví se spam, tak prostě budeme vymýšlet delší a méně předvídatelný string.
  - `date` datum kurzu
  - `tasks-repo` repozitář kde hledat zadání úkolů 
- `/%tid/config/layout`: Konfigurace stolů. Možnost vybrat z šablon (soubory v adresáři), po vybrání se ukládá k termínu. Editor JSONu se zvýrazňováním syntaxe, chyb a live náhledem stolů. Současný formát i jeho renderování vyhovuje.
- `/%tid`: Landing page pro účastnice. Vybere své místo, což je jen odkaz na následující.
- `/%tid/%pid`: Hlavní stránka pro účastnice. Nastaví své jméno, zadává svůj stav, přijímá zadání úkolů.
- `/%tid/coach`: Mapa se zobrazením stavů, poslední zadání úkolů.
- `/%tid/teacher`: Obrácená mapa se stavy a ovládání.
- `/`: Odkaz na aktuálně probíhající termíny (dnešní datum)

**Comment by benabraham** [comment]
Jasně, chce to. Prd tomu rozumim, ale přemejšlel jsem spíš o Feathers.

**Comment by benabraham** [comment]
Jinak mám nějaký představy o změnách a pokud by byla shoda, bylo by asi fajn je začlenit do tý práce na změnách rovnou.
Týkají se:

- funkcionality (např. fronta požadavků na kouče, ale i další)
- layout z hlediska interakčního designu
- layout z technologickýho pohledu (css grid)
- změna FE technologie (zvažoval jsem vue.js)

**Comment by jnv** [comment]
Ad konfigurace termínů, termín je trojice `tasks.md`, konfigurace stolů a jmen účastnic.

- tasks.md mohou být reprezentované URL do repozitáře workshopu
- konfigurace stolů se zkopíruje ze šablony (aby bylo možné začlenit lokální změny, když se šoupe se stoly apod.)
- jména účastnic se budou ukládat průběžně, jak se registrují

Na současné implementaci vidím nedostatek i ten, že není možné měnit konfiguraci stolů poté, co se účastnice zaregistrují, přestože je na to implementace teoreticky připravená (každý stůl má unikátní id), takže za mě tohle by byla fajn změna.

Ohledně synchronizace klientů, doporučuju zvážit i nějaké P2P řešení jako [GUN](http://gun.js.org/), které obstojí výpadek serveru (viz mizerné připojení ve Voxu) a hezky řeší eventuální synchronizaci stavu. Meteoru bych se doporučoval spíš vyhnout, přijde mi že jeho ekosystém dojíždí na vendor lock-in.

Ad FE technologie, Vue nebo React, zvážil bych i Polymer nebo něco jiného s web components. Jako challenge Elm nebo Reason + React.

**Comment by iBobik** [comment]
Hlasuji pro Vue (jsem ochotný s ním pomoci).

GUN vypadá velmi zajímavě. Máš s tím @jnv zkušenost? Já bych si to rád vyzkoušel.

Co je špatně z pohledu designu, @benabraham? Byl jsem u mnoha uživatelských testování a u účastnic jsem si ničeho nevšiml. :-)

Další funkce bych nedělal v první verzi, teď potřebujeme vyřešit stávající problémy a vydat verzi 1.0. Jen s nimi počítat v architektuře.

Co takhle hackaton?

**Comment by benabraham** [comment]
Říkám si, jestli by nekvalitní připojení nebylo lepší řešit aplikací rozběhnutou v lokální síti.

**Comment by lrolecek** [comment]
Podle mě bylo. Já jsem pro lokální nasazení. Teď jsme lístečkovou aplikaci dlouho nepoužil, ale můj největší zdroj stressu byl, že něco, kolem čeho se točí celý workshop, běží někde v internetu, kde nad tím nemám žádnou kontrolu a nemohu s případným výpadkem (serveru nebo připojení) nic dělat. Ve chvíli, kdy pomocí aplikaci řeším jen červený/zelený lísteček, tak to tolik nevadí. Ve chvíli, kdy se tím zadávají úkoly, je to podle mě v podstatě nutnost.

**Comment by jnv** [comment]
U lokální verze bude nepříjemné zjišťování a zadávání IP adresy, ale to by mělo být průchozí. Největší průšvih může být na korporátních wifi sítích s izolací klientů, což by odřízlo i P2P offline řešení. Nicméně nemělo by být težké zabalit celou aplikaci do nějakého binárního releasu se všemi závislostmi, který si lektor rozjede lokálně ze svého počítače. Nebo pro fajnšmekry udělat hardware appliance. 😉

@iBobik Přiznám se, že GUN jsem na reálném projektu ještě nezkoušel. Tady mi přijde zajímavý pro protože řeší synchronizaci stavu. To mi přijde důležitější než real-time komunikace. Ba co víc, pokud byste preferovali centralizovaný model se serverem, pak mi přijde zbytečné řešit komunikaci přes websockety (Feathers, Socket IO); jako vhodnější mi přijde HTTP/2 a server push.

Must-have: service worker.

**Comment by iBobik** [comment]
@jnv Pokud to používá WebRTC, tak by to mělo fungovat v sítích, kde je izolace - samo to buď komunikuje lokálně nebo nebo přes prostředníka.

Server push k tomuto neslouží, nejde tam JS aplikaci poslat něco, co si sama nevyžádala a navíc opakovaně. K tomu slouží web sockety.

K čemu přesně chceš použít service workery?

**Comment by iBobik** [comment]
A GUN je prý i realtime.

**Comment by jnv** [comment]
@iBobik Pardon, trochu jsem pomotal co mám na mysli. Vidím tu dva modely jak pojmout komunikaci mezi serverem a klienty:

1. Klasický server-klient, server má kanonický stav, klient si stahuje stav ze serveru přes HTTP nebo WebSockets (dále).
2. P2P s použitím GUN nebo jiného řešení, stav je distribuovaný mezi klienty, server funguje jako klient, řeší perzistenci stavu, příp. peer discovery. Komunikace přes websockets ([WebRTC transport je WIP](https://github.com/gundb/gun-rtc)). GUN je realtime.

V prvním případě lze komunikaci řešit přes websockets nebo přes HTTP. V případě HTTP lze použít tradiční polling a/nebo Server-Sent Events pro HTTP/2 (máš pravdu že server push slouží k něčemu jinému). SSE si trochu lépe rozumí s firewally protože udržuje obyčejné HTTP spojení a má smysl pro read-only komunikaci ze serveru, což je případ téhle aplikace (změna stavu účastnice, tj. "Mám hotovo", "Potřebuju pomoc" může být separátní request). U websocketů je zase snažší kontrolovat stav připojení klientů, nicméně je to nízkoúrovňový protokol a většina knihoven reimplementuje logiku kterou má HTTP out-of-box. Fail je, že Edge SSE stále nepodporuje, ale existují polyfilly.

Service worker v základu pro offline caching assetů, většina build nástrojů to pořeší. Šel by využít i pro push notifikace, to může být šikovné zejména pro kouče.

Zdroje k SSE:

- https://www.html5rocks.com/en/tutorials/eventsource/basics/
- https://www.smashingmagazine.com/2018/02/sse-websockets-data-flow-http2/
- [+ argument proti WS](https://samsaffron.com/archive/2015/12/29/websockets-caution-required) (2015)

**Comment by iBobik** [comment]
Aha, už rozumím.

Jestli to řešít přes websockety nebo longpooling je nakonec celkem jedno, protože na to určitě budeme chtít použít nějakou knihovnu, která se napojí na MVC, protože nejlepší kód je ten, který nenapíšeme.

Service workery bych vzal až úplně na konec, protože to ohledně offline nic nepřinese - i dnes musí tu aplikaci poprvé otevřít a pak už to nechat v tabu. Benefit jsou notifikace pro kouče při neaktvní stránce a to stejně zatím jen pro Android.


Honza Pobořil
https://honza.poboril.cz

**Comment by iBobik** [comment]
Tak jsem teď GUN otestoval a nefunguje po lokální síti bez serveru (P2P). Ale když si ten server pustí lokálně, tak by to mohlo být použitelné (jednoduchý node skript).

**Comment by jnv** [comment]
Díky za otestování, trochu jsem to čekal vzhledem k tomu že ještě nemají hotový RTC transport. Nicméně základem je pořád distribuovaná databáze, takže server se může resynchronizovat z klienta.

**Comment by iBobik** [comment]
Nějaké experimenty tady už byly, jen nejsou aktuální.
https://github.com/gundb/gun-rtc <https://github.com/gundb/gun-rtc>

Každopádně vypadá GUN perspektivně a postavil bych to na něm.



Honza Pobořil
https://honza.poboril.cz

**Comment by iBobik** [comment]
Aktualizovaná verze zadání pro hackaton: https://github.com/czechitas/listecky/issues/1
